services:
  apartments:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/apartments-app
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

  postgres:
    image: postgres:17.2-alpine
    container_name: postgresdb
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apartments-app
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
    depends_on:
      - "postgres"
