spring:
  application:
    name: apartments
  datasource:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/apartments-app
      username: username
      password: "password"
      pool-size: 30
